language: node_js
sudo: false
services:
  - redis-server

node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"

cache:
  directories:
    - node_modules

after_script:
  - npm run lint
  - mkdir -p coverage
  - npm run coverage
  - npm run publish-coverage
